package model;
// Generated 2018/9/5 �W�� 10:19:24 by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BlacklistId generated by hbm2java
 */
@Embeddable
public class BlacklistId implements java.io.Serializable {

	private int memberid;
	private int blackid;

	public BlacklistId() {
	}

	public BlacklistId(int memberid, int blackid) {
		this.memberid = memberid;
		this.blackid = blackid;
	}

	@Column(name = "memberid", nullable = false)
	public int getMemberid() {
		return this.memberid;
	}

	public void setMemberid(int memberid) {
		this.memberid = memberid;
	}

	@Column(name = "blackid", nullable = false)
	public int getBlackid() {
		return this.blackid;
	}

	public void setBlackid(int blackid) {
		this.blackid = blackid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BlacklistId))
			return false;
		BlacklistId castOther = (BlacklistId) other;

		return (this.getMemberid() == castOther.getMemberid()) && (this.getBlackid() == castOther.getBlackid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMemberid();
		result = 37 * result + this.getBlackid();
		return result;
	}

}
