package model;
// Generated 2018/9/5 �W�� 10:19:24 by Hibernate Tools 5.2.8.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Blacklist generated by hbm2java
 */
@Entity
@Table(name = "blacklist", schema = "dbo", catalog = "wegether", uniqueConstraints = @UniqueConstraint(columnNames = {
		"memberid", "blackid" }))
public class BlacklistBean implements java.io.Serializable {

	private BlacklistId id;
	private MemberBean memberByBlackid;
	private MemberBean memberByMemberid;

	public BlacklistBean() {
	}

	public BlacklistBean(BlacklistId id, MemberBean memberByBlackid, MemberBean memberByMemberid) {
		this.id = id;
		this.memberByBlackid = memberByBlackid;
		this.memberByMemberid = memberByMemberid;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "memberid", column = @Column(name = "memberid", nullable = false)),
			@AttributeOverride(name = "blackid", column = @Column(name = "blackid", nullable = false)) })
	public BlacklistId getId() {
		return this.id;
	}

	public void setId(BlacklistId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "blackid", nullable = false, insertable = false, updatable = false)
	public MemberBean getMemberByBlackid() {
		return this.memberByBlackid;
	}

	public void setMemberByBlackid(MemberBean memberByBlackid) {
		this.memberByBlackid = memberByBlackid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "memberid", nullable = false, insertable = false, updatable = false)
	public MemberBean getMemberByMemberid() {
		return this.memberByMemberid;
	}

	public void setMemberByMemberid(MemberBean memberByMemberid) {
		this.memberByMemberid = memberByMemberid;
	}

}
