package model;
// Generated 2018/9/5 �W�� 10:19:24 by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TrackactivityId generated by hbm2java
 */
@Embeddable
public class TrackactivityId implements java.io.Serializable {

	private int memberid;
	private int activityid;

	public TrackactivityId() {
	}

	public TrackactivityId(int memberid, int activityid) {
		this.memberid = memberid;
		this.activityid = activityid;
	}

	@Column(name = "memberid", nullable = false)
	public int getMemberid() {
		return this.memberid;
	}

	public void setMemberid(int memberid) {
		this.memberid = memberid;
	}

	@Column(name = "activityid", nullable = false)
	public int getActivityid() {
		return this.activityid;
	}

	public void setActivityid(int activityid) {
		this.activityid = activityid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TrackactivityId))
			return false;
		TrackactivityId castOther = (TrackactivityId) other;

		return (this.getMemberid() == castOther.getMemberid()) && (this.getActivityid() == castOther.getActivityid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMemberid();
		result = 37 * result + this.getActivityid();
		return result;
	}

}
