package model;
// Generated 2018/9/5 �W�� 09:44:45 by Hibernate Tools 5.2.8.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Trackmember generated by hbm2java
 */
@Entity
@Table(name = "trackmember", schema = "dbo", catalog = "wegether")
public class TrackmemberBean implements java.io.Serializable {
	
	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "memberid", column = @Column(name = "memberid", nullable = false)),
			@AttributeOverride(name = "fanid", column = @Column(name = "fanid", nullable = false)) })
	private TrackmemberId id;
	
	@ManyToOne
	@JoinColumn(name = "memberid", insertable = false, updatable = false)
	private MemberBean memberByMemberid;


	public TrackmemberBean() {
	}

	public TrackmemberBean(TrackmemberId id) {
		this.id = id;
	}

	
	public TrackmemberId getId() {
		return this.id;
	}

	public void setId(TrackmemberId id) {
		this.id = id;
	}
	
	
	public MemberBean getMemberByMemberid() {
		return this.memberByMemberid;
	}

	public void setMemberByMemberid(MemberBean memberByMemberid) {
		this.memberByMemberid = memberByMemberid;
	}
	
	@Override
	public String toString() {
			return String.format("[memberid : %s , fanid : %s]", id.getMemberid(), id.getFanid());
			
	}

}
