package model;
// Generated 2018/9/5 �W�� 09:44:45 by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TrackmemberId generated by hbm2java
 */
@Embeddable
public class TrackmemberId implements java.io.Serializable {

	private int memberid;
	private int fanid;

	public TrackmemberId() {
	}

	public TrackmemberId(int memberid, int fanid) {
		this.memberid = memberid;
		this.fanid = fanid;
	}

	@Column(name = "memberid", nullable = false)
	public int getMemberid() {
		return this.memberid;
	}

	public void setMemberid(int memberid) {
		this.memberid = memberid;
	}

	@Column(name = "fanid", nullable = false)
	public int getFanid() {
		return this.fanid;
	}

	public void setFanid(int fanid) {
		this.fanid = fanid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TrackmemberId))
			return false;
		TrackmemberId castOther = (TrackmemberId) other;

		return (this.getMemberid() == castOther.getMemberid()) && (this.getFanid() == castOther.getFanid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMemberid();
		result = 37 * result + this.getFanid();
		return result;
	}

}
